version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the server config json file...
      - node config/build_server_config.js > config/server_config.json
artifacts:
  files:
    - config/server_config.json